import {
  apply_factor,
  close_orders,
  create_orders,
  create_orders_builder,
  create_deposits,
  default_store_program,
  Market,
  MarketGraph,
  Position,
  Pubkey,
  TradeEvent,
  update_orders,
  create_withdrawals,
  create_shifts,
  Glv,
  create_glv_deposits,
  create_glv_withdrawals,
} from "../../pkg/index.js";

function toBase64(data: number[]): string {
  const uint8 = new Uint8Array(data);

  const binary = String.fromCharCode(...uint8);

  return btoa(binary);
}

// Apply factor.
const result = apply_factor(123n, 90_000_000_000_000_000_000n);
console.log("apply factor:", result);

// Get default store program and store address.
console.log(default_store_program());

const encodedMarket =
  "277VNwDjxpoA/xEAAAAAAAAAAAAAAAAAR01YL1VTRFtXU09MLVVTRENdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMKhMtqEXwT4SYzrEExJSClgE9XJbT3T05sgeb6VBv6x6mNMmaw6BGtCT+KrCHsxK2VZ5qQu5ZkWkmbafJPIrWMGm4hX/quBhPtof2NGGMA12sQ53BrrO1WYoPAAAAAAAcb6evO+2606PWXzaqvJdDGxu+TC0vbg5HymAgNFL11hqiedLXM7yPHAFKs3olYkIRypdssZnsYuonnN3lj2njUBAAAAAAAAAAAAAAAAAAAAAAAgxlq8jtcKAAAAAAAAAAAW0L4oAAAAAAAAAAAAAAAALKB9UQAAAAAAAAAAAAAAAABYxR/1ccsDAAAAAAAAAAAAxS68orEAAAAAAAAAAAAAAEcOobD4AAAAAAAAAAAAAAAQYy1ex2sFAAAAAAAAAAAAEGMtXsdrBQAAAAAAAAAAAGSns7bgDQAAAAAAAAAAAMgXqAQAAAAAAAAAAAAAAADIF6gEAAAAAAAAAAAAAAAAALLTWVvwBgAAAAAAAAAAAACy01lb8AYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACDGWryO1woAAAAAAAAAAEQpNToAAAAAAAAAAAAAAACIUmp0AAAAAAAAAAAAAAAAAFjFH/VxywMAAAAAAAAAAAAEv8kbjgAAAAAAAAAAAAAAhp6uKdUAAAAAAAAAAAAAAFjFH/VxywMAAAAAAAAAAAAUu/CKxgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArCP8BgAAAAAAAAAAAAAAAABYxR/1ccsDAAAAAAAAAIN9zBCWAQAAAAAAAAAAAACDfcwQlgEAAAAAAAAAAAAAAAAQYy1ex2sFAAAAAAAAAAAAEGMtXsdrBQAAAAAAAAAAAEwKoobVEAQAAAAAAAAAAABMCqKG1RAEAAAAAAAAAIN9zBCWAQAAAAAAAAAAAACDfcwQlgEAAAAAAAAAAAAApCSJwr8DAAAAAAAAAAAAAKQkicK/AwAAAAAAAAAAAAAAABBjLV7HawUAAAAAAAAAACBKqdEBAAAAAAAAAAAAAFy1Fk3iAgAAAAAAAAAAAADvBg1iBwAAAAAAAAAAAAAA4R6AEQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJCdztqCNwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZICdYw6GAwAAAAAAAAAAAHA7G9KqQAMAAAAAAAAAAABwOxvSqkADAAAAAAAAAAAAcDsb0qpAAwAAAAAAAAAAAJRslB2AcAIAAAAAAAAAAACUbJQdgHACAAAAAAAAAAAAiLEWr+O1AgAAAAAAAAAAAIixFq/jtQIAAAAAAAAAAABkgJ1jDoYDAAAAAAAAAAAAZICdYw6GAwAAAAAAAAAAAHA7G9KqQAMAAAAAAAAAAABwOxvSqkADAAAAAAAAAAC+L3A/AwAAAAAAAAAAAAAAiFJqdAAAAAAAAAAAAAAAAAAATcUFWuMeOSUAAAAAAAAAAE3FBVrjHjklAAAAAAAAAAByaQZkbulbKQAAAAAAAAAAcmkGZG7pWykAAAAAAADKmjsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAAAAAAGAAAAAAAAAPYCAAAAAAAABQAAAAAAAAA+AQAAAAAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArrw0cRoAAAAAAAAAAAAAANbDT4gMAAAAAAAAAAAAAAAMCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEySRgEAAAAAAAAAAAAAAAAJHNQKAAAAAAAAAAAAAAAADAsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACUaggEAAAAAAAAAAAAAAAA7ox4AAAAAAAAAAAAAAAAAPYKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB6UZy9XHf2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADs/LdEaOePVwYAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9goAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADZH9OyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAR6A9pgQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF4Vm1cFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADrXMJddf8DmQAAAAAAAAAAjuUSQeuzngUAAAAAAAAAAAcLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHBm4K185GwAAAAAAAAAAAAfP2qVuDwEAAAAAAAAAAAAHCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACB+DiLKUwIAAAAAAAAAAABsU2LMcZ0AAAAAAAAAAAAABwsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJXI0a30hKAAAAAAAAAAAAFIPYIu8cAgAAAAAAAAAAAAcLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0phnIsajggAAAAAAAAAAAMHQDXpLaAAAAAAAAAAAAAD2CgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFey5gcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACuwRQcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3HVVKIxpaiMbAAAAAAAAAEMZgdUYPK12BgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMCwAAAAAAACevCWgAAAAAqfQPaAAAAAAnrwloAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAsAAAAAAABgAgAAAAAAAEcuf5oaAAAAIoCjkwwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMCwAAAAAAAAAAAAAAAAAADAsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACuvDRxGgAAAAAAAAAAAAAA1sNPiAwAAAAAAAAAAAAAAAwLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATJJGAQAAAAAAAAAAAAAAAAkc1AoAAAAAAAAAAAAAAAAMCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJRqCAQAAAAAAAAAAAAAAADujHgAAAAAAAAAAAAAAAAA9goAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHpRnL1cd/YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOz8t0Ro549XBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAD2CgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANkf07IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHoD2mBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXhWbVwUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOtcwl11/wOZAAAAAAAAAACO5RJB67OeBQAAAAAAAAAABwsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcGbgrXzkbAAAAAAAAAAAAB8/apW4PAQAAAAAAAAAAAAcLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIH4OIspTAgAAAAAAAAAAAGxTYsxxnQAAAAAAAAAAAAAHCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlcjRrfSEoAAAAAAAAAAAAUg9gi7xwCAAAAAAAAAAAABwsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADSmGcixqOCAAAAAAAAAAAAwdANektoAAAAAAAAAAAAAPYKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAV7LmBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK7BFBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADcdVUojGlqIxsAAAAAAAAAQxmB1Rg8rXYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwLAAAAAAAAJ68JaAAAAACp9A9oAAAAACevCWgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMCwAAAAAAAGACAAAAAAAARy5/mhoAAAAigKOTDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";

const encodedPosition =
  "qryP5HpA99AAAKonnS1zO8jxwBSrN6JWJCEcqXbLGZ7GLqJ5zd5Y9p41AQAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMKhMtqEXwT4SYzrEExJSClgE9XJbT3T05sgeb6VBv6xBpuIV/6rgYT7aH9jRhjANdrEOdwa6ztVmKDwAAAAAAEBAAAAAAAAAAIAAAAAAAAABAAAAAAAAAADAAAAAAAAAABe0LIAAAAAAAAAAAAAAAAAKd4HAAAAAAAAAAAAAAAAAADQafqNC/LzAAAAAAAAAAAATDG42aeYAAAAAAAAAAAAAEvkKAAbAAAAAAAAAAAAAACC3+QNRwAAAAAAAAAAAACg8AOnvQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";

const encodedTradeEvent =
  "vdt/007mYe4EAAAAAAAAAIkEAAAAAAAAiuHztSTsoCdXd7+bFfgKkpK2s8Ekmu0xYxJ1oDwLWIqqJ50tczvI8cAUqzeiViQhHKl2yxmexi6iec3eWPaeNcKhMtqEXwT4SYzrEExJSClgE9XJbT3T05sgeb6VBv6xqwA6yS5PboFFwCb6q63SgaG0W0GzASnj1U+pUGxKJsewFnd5vBDNdtngw5sDKxLvMoy5yp++cuXkfJHeKTQhN2ticm3+24sDA+6uFBYcYV5mId2KbkIVNp0FQMN2GYEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB498JoAAAAABLx0hUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACJBAAAAAAAAHj3wmgAAAAAEvHSFQAAAAAAAAAAAAAAAAYOKqkEAAAAAAAAAAAAAADN95EFAAAAAAAAAAAAAAAAAEjLH5rz1n1IBgAAAAAAAKXVoc0bPUcIAAAAAAAAAAAn98yvXHgRAAAAAAAAAAAAUNQN8hDqlQAAAAAAAAAAAPescRKCWnMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoDI0HFkBAAAAAAAAAAAAAGCwVWJZAQAAAAAAAAAAAABAnF4AsBQAAAAAAAAAAAAAAO8SSLAUAAAAAAAAAAAAAACOC27tWgAAAAAAAAAAAAAAF11d8VoAAAAAAAAAAAAAhkhbHFkBAAAAAAAAAAAAABZ3LQg0UbYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADfOgEAAAAAAAAAAAAAAAAA8oYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==";

const encodedGlv =
  "iK6ds8ubnPMA/v4AAAAAAKonnS1zO8jxwBSrN6JWJCEcqXbLGZ7GLqJ5zd5Y9p41ZbZuOMAEg47Om+mqV/tR1crIjeZ//KFccoeAdXiNS5QGm4hX/quBhPtof2NGGMA12sQ53BrrO1WYoPAAAAAAAQcj74q5WbnXt/b6IzhPLwdXSLZffX5dJpDN1Zk+orNA+Iu5aAAAAAAAypo7AAAAABAOAAAAAAAAAABkp7O24A0AAAAAAAAAAAAAEGMtXsdrBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC7jd9VgeyHS7lYKmObHwXyqx/cQ2dP2tTt6b+MVR/U0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeQyuoCS7VUfaFpASDPHAjYHTgXLOQZQ2YP/5VfgD5VQCA4Dd5wxEAAQAAAAAAAAAAAAB0HkDoTx6XnQEAAAAAYACj5RsAAAAAAAAAAAAAADi0ZP1xFM4ldJADAj2TRiJbRQnNMX3z74v6RgZyWlp+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASGbGtWBeSv8b/dAftfqjNLwuiFUC4u1mdYYx/h8byMMAgOA3ecMRAAEAAAAAAAAAAAAAdB5A6E8el50BAAAAAJ+2Ab82CgAAAAAAAAAAAABSXtxoSviz1FkveERtJAWntVqlF432//AmMD5i5dTGbQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGCNmi8XPIi7aY748QjkOGj9muO+73wMcyEuvl9IGDRzAIDgN3nDEQABAAAAAAAAAAAAAHQeQOhPHpedAQAAAABS0/4eCwMAAAAAAAAAAAAApZS3wm1h3uxWxjJ7n9Te0Cmt3zXSWDIQZGY2Qqi1jxMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACrfUrrLR0qCyfvdmYEYK8oyB6aXQa2SMBA/K0hcK1NIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANdb70+czShFcTfYXtzwYz7WPiy8TFKoIy62wxIxAkaMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5JWeOnK/Iz+nr3YEcD4m6fmOJT/3od3Hqwyvq5XyouEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD6YRhMby8o9IhCtcLt5RO4hr2nVI6PVYMsqZ5n6MfOkwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPrGdCeafpKVP3siWEYrL01J33yp2nRzAlL/RX8I2fwCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAA==";

const supply = 79185141665179n;
const glvTokenSupply = 655497657135387n;

// Decode Market from base64 data.
const market = Market.decode_from_base64(encodedMarket);
const model = market.to_model(supply);
const prices = {
  index_token: {
    min: 1560019900000n,
    max: 1561071800000n,
  },
  long_token: {
    min: 14776017000000n,
    max: 14778132000000n,
  },
  short_token: {
    min: 99989200000000n,
    max: 100004200000000n,
  },
};

// Calculate market token price.
const price = model.market_token_price({
  prices,
  maximize: true,
  pnl_factor: "max_after_deposit",
});
console.log("market token price:", price);

// Calculate market status.
console.log("market status:", model.status({ prices }));

// Create a MarketGraph.
const graph = new MarketGraph({
  swap_estimation_params: {
    value: 1_000_000_000_000_000_000_000n,
    base_cost: 1_000_000_000_000_000_000n,
  },
  max_steps: 5,
});

// Insert market from base64 data.
graph.insert_market_from_base64(encodedMarket, supply);

console.log(graph.market_tokens().map((token) => token.toString()));

const gmx = "GmxDsqjKYUrwgbvccGrpF1LoyHPUq8FQqT1FJfkvrMfY";
const wsol = "So11111111111111111111111111111111111111112";
const usdc = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v";

graph.update_token_price(gmx, { ...prices.index_token });
graph.update_token_price(wsol, { ...prices.long_token });
graph.update_token_price(usdc, { ...prices.short_token });

// Calculate best swap path.
const { path } = graph.best_swap_path(
  "So11111111111111111111111111111111111111112",
  "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
  false
);
console.log(path.map((token) => new Pubkey(token).toString()));

// Decode position from base64 data.
const position = Position.decode_from_base64(encodedPosition);
const positionModel = position.to_model(model);
console.log("size:", positionModel.size());
console.log("size_in_tokens:", positionModel.size_in_tokens());
console.log("collateral amount:", positionModel.collateral_amount());
console.log("status:", positionModel.status(prices));

// Simulate order.
const simulator = graph.to_simulator();
const simulationOutput = simulator.simulate_order(
  {
    kind: "MarketIncrease",
    params: {
      market_token: "E6kfBQcdHL3fdWNaydrWViXVtQLTgpxzZicLy98ZNc5v",
      is_long: true,
      size: 100_000_000_000_000_000_000_000n,
      amount: 10_000_000n,
    },
    collateral_or_swap_out_token: wsol,
  },
  position
);
console.log("simulation:", simulationOutput.increase());
let outputPositionModel = simulationOutput.position_model()!;
console.log("output position:", outputPositionModel.size());

// Create order.
const recentBlockhash = "3KarAamyLd6dFFmMsh79fXjrdAWp5DB6dxF3BgLK3SuM";
const payer = "11111111111111111111111111111112";
// Use the real market token from the decoded/inserted market
const marketToken = market.market_token_address();
const transactions = create_orders(
  "MarketIncrease",
  [
    {
      market_token: marketToken,
      is_long: true,
      size: 100_000_000_000_000_000_000_000n,
      amount: 10_000_000n,
    },
  ],
  {
    recent_blockhash: recentBlockhash,
    payer,
    collateral_or_swap_out_token: wsol,
    compute_unit_price_micro_lamports: 2000000,
    hints: new Map([
      [
        marketToken,
        {
          long_token: wsol,
          short_token: usdc,
        },
      ],
    ]),
    transaction_group: {
      memo: "aBsLTf/2DhUG5rg79iU+vUDAXkk=",
    },
  }
);

console.log("create orders");
for (const batch of transactions.serialize()) {
  for (const txn of batch) {
    console.log(toBase64(txn));
  }
}

// Create multiple orders.
const multipleBuilder = create_orders_builder(
  "MarketIncrease",
  [
    {
      market_token: marketToken,
      is_long: true,
      size: 100_000_000_000_000_000_000_000n,
      amount: 10_000_000n,
    },
  ],
  {
    recent_blockhash: recentBlockhash,
    payer,
    collateral_or_swap_out_token: wsol,
    hints: new Map([
      [
        marketToken,
        {
          long_token: wsol,
          short_token: usdc,
        },
      ],
    ]),
  }
);
const tpBuilder = create_orders_builder(
  "LimitDecrease",
  [
    {
      market_token: marketToken,
      is_long: true,
      size: 100_000_000_000_000_000_000_000n,
      amount: 10_000_000n,
      trigger_price: 23_000_000_000_000n,
    },
  ],
  {
    recent_blockhash: recentBlockhash,
    payer,
    collateral_or_swap_out_token: wsol,
    hints: new Map([
      [
        marketToken,
        {
          long_token: wsol,
          short_token: usdc,
        },
      ],
    ]),
  }
);
const slBuilder = create_orders_builder(
  "StopLossDecrease",
  [
    {
      market_token: marketToken,
      is_long: true,
      size: 100_000_000_000_000_000_000_000n,
      amount: 10_000_000n,
      trigger_price: 10_000_000_000_000n,
    },
  ],
  {
    recent_blockhash: recentBlockhash,
    payer,
    collateral_or_swap_out_token: wsol,
    hints: new Map([
      [
        marketToken,
        {
          long_token: wsol,
          short_token: usdc,
        },
      ],
    ]),
  }
);

multipleBuilder.merge(tpBuilder);
multipleBuilder.merge(slBuilder);

const multipleTransactions = multipleBuilder.build_with_options(
  {},
  {
    recent_blockhash: recentBlockhash,
    compute_unit_price_micro_lamports: 2000000,
  }
);

console.log("create multiple orders");

for (const batch of multipleTransactions.serialize()) {
  for (const txn of batch) {
    console.log(toBase64(txn));
  }
}

// Close orders.
const closeOrders = close_orders({
  recent_blockhash: recentBlockhash,
  payer,
  orders: new Map([
    [
      "11111111111111111111111111111113",
      {
        owner: payer,
        receiver: payer,
        rent_receiver: payer,
        referrer: undefined,
        initial_collateral_token: wsol,
        final_output_token: undefined,
        long_token: wsol,
        short_token: usdc,
        should_unwrap_native_token: true,
        callback: undefined,
      },
    ],
    [
      "11111111111111111111111111111114",
      {
        owner: payer,
        receiver: payer,
        rent_receiver: payer,
        referrer: "11111111111111111111111111111115",
        initial_collateral_token: wsol,
        final_output_token: undefined,
        long_token: usdc,
        short_token: usdc,
        should_unwrap_native_token: false,
        callback: undefined,
      },
    ],
  ]),
});

console.log("close orders");
for (const batch of closeOrders.serialize()) {
  for (const txn of batch) {
    console.log(toBase64(txn));
  }
}

// Update orders.
const updateOrders = update_orders({
  recent_blockhash: recentBlockhash,
  payer,
  orders: new Map([
    [
      "11111111111111111111111111111113",
      {
        params: {
          size_delta_value: 100_000_000_000_000_000_000_000n,
        },
        hint: {
          market_token: market.market_token_address(),
          callback: undefined,
        },
      },
    ],
    [
      "11111111111111111111111111111114",
      {
        params: {
          trigger_price: 1561071800000n,
        },
        hint: {
          market_token: market.market_token_address(),
          callback: undefined,
        },
      },
    ],
  ]),
});

console.log("update orders");
for (const batch of updateOrders.serialize()) {
  for (const txn of batch) {
    console.log(toBase64(txn));
  }
}

console.log("create position from trade event");
const tradeEvent =
  TradeEvent.decode_from_base64_with_options(encodedTradeEvent);
const tradeEventPosition = tradeEvent.to_position_model(model);
console.log("size:", tradeEventPosition.size());
console.log("size_in_tokens:", tradeEventPosition.size_in_tokens());
console.log("collateral amount:", tradeEventPosition.collateral_amount());

// Create deposits (minimal check)
const depositParams = {
  market_token: marketToken,
  receiver: payer,
  long_pay_token: wsol,
  short_pay_token: usdc,
  long_swap_path: [],
  short_swap_path: [],
  long_pay_amount: 1_000_000n,
  short_pay_amount: 0n,
  min_receive_amount: 0n,
  unwrap_native_on_receive: true,
};
const depositGroup = create_deposits([depositParams], {
  recent_blockhash: recentBlockhash,
  payer,
  hints: new Map([
    [
      marketToken,
      {
        pool_tokens: {
          long_token: wsol,
          short_token: usdc,
        },
      },
    ],
  ]),
  transaction_group: {},
});

console.log("create deposits");
for (const batch of depositGroup.serialize()) {
  for (const txn of batch) {
    console.log(toBase64(txn));
  }
}

// Simulate deposit.
const depositSimulationOutput = simulator.simulate_deposit({
  params: depositParams,
});

console.log(`deposit simulation: ${depositSimulationOutput.report()}`);

// Create withdrawals
const withdrawalParams = {
  market_token: marketToken,
  market_token_amount: 2_000_000_000n,
};
const withdrawalGroup = create_withdrawals([withdrawalParams], {
  recent_blockhash: recentBlockhash,
  payer,
  hints: new Map([
    [
      marketToken,
      {
        pool_tokens: {
          long_token: wsol,
          short_token: usdc,
        },
      },
    ],
  ]),
  transaction_group: {},
});

console.log("create withdrawals");
for (const batch of withdrawalGroup.serialize()) {
  for (const txn of batch) {
    console.log(toBase64(txn));
  }
}

// Simulate withdrawal.
const withdrawalSimulationOutput = simulator.simulate_withdrawal({
  params: withdrawalParams,
});

console.log(`withdrawal simulation: ${withdrawalSimulationOutput.report()}`);

// Create shifts.
const shiftParams = {
  from_market_token: marketToken,
  to_market_token: "BwN2FWixP5JyKjJNyD1YcRKN1XhgvFtnzrPrkfyb4DkW",
  from_market_token_amount: 2_000_000_000n,
};
const shiftGroup = create_shifts([shiftParams], {
  recent_blockhash: recentBlockhash,
  payer,
  transaction_group: {},
});

console.log("create shifts");
for (const batch of shiftGroup.serialize()) {
  for (const txn of batch) {
    console.log(toBase64(txn));
  }
}

// Decode GLV from base64 data.
const glv = Glv.decode_from_base64_with_options(encodedGlv);
console.log(`GLV token address: ${glv.glv_token_address()}`);
console.log(`GLV long token address: ${glv.long_token_address()}`);
console.log(`GLV short token address: ${glv.short_token_address()}`);
const glvModel = glv.to_model(glvTokenSupply);
console.log(`GLV token supply: ${glvModel.supply()}`);

// Insert GLV into simulator.
const glvToken = glvModel.glv_token_address();
simulator.insert_glv(glvModel);
console.log(
  `Get GLV token supply from simulator: ${simulator
    .get_glv(glvToken)
    ?.supply()}`
);

// Create GLV deposits.
const glvDepositParams = {
  glv_token: glvToken,
  market_token: marketToken,
  receiver: payer,
  long_pay_token: wsol,
  short_pay_token: usdc,
  long_swap_path: [],
  short_swap_path: [],
  long_pay_amount: 1_000_000n,
  short_pay_amount: 0n,
  min_receive_amount: 0n,
  unwrap_native_on_receive: true,
};
const glvDepositGroup = create_glv_deposits([glvDepositParams], {
  recent_blockhash: recentBlockhash,
  payer,
  hints: new Map([
    [
      glvToken,
      {
        pool_tokens: {
          long_token: wsol,
          short_token: usdc,
        },
      },
    ],
  ]),
  transaction_group: {},
});

console.log("create GLV deposits");
for (const batch of glvDepositGroup.serialize()) {
  for (const txn of batch) {
    console.log(toBase64(txn));
  }
}

// Create GLV withdrawals
const glvWithdrawalParams = {
  glv_token: glvToken,
  market_token: marketToken,
  glv_token_amount: 2_000_000_000n,
};
const glvWithdrawalGroup = create_glv_withdrawals([glvWithdrawalParams], {
  recent_blockhash: recentBlockhash,
  payer,
  hints: new Map([
    [
      glvToken,
      {
        pool_tokens: {
          long_token: wsol,
          short_token: usdc,
        },
      },
    ],
  ]),
  transaction_group: {},
});

console.log("create GLV withdrawals");
for (const batch of glvWithdrawalGroup.serialize()) {
  for (const txn of batch) {
    console.log(toBase64(txn));
  }
}

// Builder fee: close_orders with settle_builder_fee populated.
const builderPubkey = "22222222222222222222222222222222";
const finalOutputToken = wsol;
const escrowPubkey = "33333333333333333333333333333333";
const closeOrdersWithFee = close_orders({
  recent_blockhash: recentBlockhash,
  payer,
  orders: new Map([
    [
      "11111111111111111111111111111116",
      {
        owner: payer,
        receiver: payer,
        rent_receiver: payer,
        referrer: undefined,
        initial_collateral_token: wsol,
        final_output_token: wsol,
        long_token: wsol,
        short_token: usdc,
        should_unwrap_native_token: true,
        callback: undefined,
      },
    ],
  ]),
  settle_builder_fee: new Map([
    [
      "11111111111111111111111111111116",
      {
        builder_fee_amount: 1_000_000n,
        builder: builderPubkey,
        final_output_token: finalOutputToken,
        escrow: escrowPubkey,
      },
    ],
  ]),
});

console.log("close orders with settle_builder_fee");
for (const batch of closeOrdersWithFee.serialize()) {
  for (const txn of batch) {
    console.log(toBase64(txn));
  }
}

// Builder fee: close_orders with settle_builder_fee omitted (None path).
const closeOrdersNoFee = close_orders({
  recent_blockhash: recentBlockhash,
  payer,
  orders: new Map([
    [
      "11111111111111111111111111111117",
      {
        owner: payer,
        receiver: payer,
        rent_receiver: payer,
        referrer: undefined,
        initial_collateral_token: wsol,
        final_output_token: undefined,
        long_token: wsol,
        short_token: usdc,
        should_unwrap_native_token: true,
        callback: undefined,
      },
    ],
  ]),
});

console.log("close orders without settle_builder_fee");
for (const batch of closeOrdersNoFee.serialize()) {
  for (const txn of batch) {
    console.log(toBase64(txn));
  }
}

// Builder fee: create_orders_builder with set_builder_fee.
const builderFeeBuilder = create_orders_builder(
  "MarketIncrease",
  [
    {
      market_token: marketToken,
      is_long: true,
      size: 50_000_000_000_000_000_000_000n,
      amount: 5_000_000n,
    },
  ],
  {
    recent_blockhash: recentBlockhash,
    payer,
    collateral_or_swap_out_token: wsol,
    hints: new Map([
      [
        marketToken,
        {
          long_token: wsol,
          short_token: usdc,
        },
      ],
    ]),
    set_builder_fee: {
      builder: builderPubkey,
      expected_factor: 1_000_000_000_000_000_000n,
      final_output_token: finalOutputToken,
    },
  }
);

const builderFeeTransactions = builderFeeBuilder.build_with_options(
  {},
  {
    recent_blockhash: recentBlockhash,
    compute_unit_price_micro_lamports: 2000000,
  }
);

console.log("create orders builder with set_builder_fee");
for (const batch of builderFeeTransactions.serialize()) {
  for (const txn of batch) {
    console.log(toBase64(txn));
  }
}

// Builder fee: create_orders_builder without set_builder_fee (None path).
const noBuilderFeeBuilder = create_orders_builder(
  "MarketIncrease",
  [
    {
      market_token: marketToken,
      is_long: true,
      size: 50_000_000_000_000_000_000_000n,
      amount: 5_000_000n,
    },
  ],
  {
    recent_blockhash: recentBlockhash,
    payer,
    collateral_or_swap_out_token: wsol,
    hints: new Map([
      [
        marketToken,
        {
          long_token: wsol,
          short_token: usdc,
        },
      ],
    ]),
  }
);

const noBuilderFeeTransactions = noBuilderFeeBuilder.build_with_options(
  {},
  {
    recent_blockhash: recentBlockhash,
    compute_unit_price_micro_lamports: 2000000,
  }
);

console.log("create orders builder without set_builder_fee");
for (const batch of noBuilderFeeTransactions.serialize()) {
  for (const txn of batch) {
    console.log(toBase64(txn));
  }
}
